---

- name: actions to setup and run and tear down project
  hosts: all
  tasks:
    - name: install git if necessary
      ansible.builtin.package:
        name: git
        state: latest
    - name: clone my repo
      git:
        repo: https://github.com/2105-may24-devops/davidp-project0.git
        dest: /home/davidp/davidp-project0
        version: main
    - name: is pip installed
      package:
        name: python3-pip
        state: latest
    - name: is python3 installed
      package:
        name: python3
        state: latest
    - name: install virtualenv
      pip:
        name: virtualenv
        executable: "pip3"
        state: latest
